---
deployment:
  tasks:
    # 1. Instalar/atualizar dependencias Python
    - export DEPLOYPATH=/home/mwxntafa/lecasuerp/
    - /bin/bash -c "source /home/mwxntafa/virtualenv/lecasuerp/3.11/bin/activate && pip install -r $DEPLOYPATH/requirements.txt --quiet"
    # 2. Reiniciar o Python App (Passenger)
    - /bin/bash -c "touch /home/mwxntafa/lecasuerp/tmp/restart.txt"
